language: ruby
rvm:
 - '2.4.6'
 - '2.5.5'
cache: bundler
addons:
  postgresql: '10'
after_script: bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/d69f1b2b4c21a45fd023
    on_success: change
    on_failure: always
    on_start: never
